name: CMake Build

on:
  pull_request:
    branches: [ main, develop ]

jobs:

  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Configure
        run: cmake -S . -B build -G "Visual Studio 17 2022"

      - name: Build
        run: cmake --build build --config Release
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
            name: windows-build
            path: build/Release


  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            libx11-dev \
            libxext-dev \
            libxrandr-dev \
            libxcursor-dev \
            libxi-dev \
            libxinerama-dev \
            libxss-dev \
            libxtst-dev \
            libgl1-mesa-dev \
            libasound2-dev \
            libpulse-dev \
            libwayland-dev \
            libxkbcommon-dev \
            wayland-protocols

      - name: Configure
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
            name: linux-build
            path: build


  build-web:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: latest

      - name: Configure (Web)
        run: cmake --preset web-release

      - name: Build (Web)
        run: cmake --build --preset build-web

      - name: Diable Jekyll
        run: touch build/web/.nojekyll

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: build/web

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web