name: CMake Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:

  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Configure
        run: cmake -S . -B build -G "Visual Studio 17 2022"

      - name: Build
        run: cmake --build build --config Release


  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            libx11-dev \
            libxext-dev \
            libxrandr-dev \
            libxcursor-dev \
            libxi-dev \
            libxinerama-dev \
            libxss-dev \
            libgl1-mesa-dev \
            libasound2-dev \
            libpulse-dev \
            libwayland-dev \
            libxkbcommon-dev \
            wayland-protocols

      - name: Configure
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build